services:
  fab:
    build:
      context: .
      target: fab-dev
    volumes:
      - .:/fab:cached
    command: sleep infinity
    environment:
      - DATABASE_URL=postgresql://postgres:password@fab-db:5432/fab


  fab-db:
    image: postgres
    environment:
     - POSTGRES_PASSWORD=password
