services:
  fab-dc:
    hostname: fab-dc
    container_name: fab-dc
    build:
      context: ../funding-service-design-fund-application-builder
      dockerfile: Dockerfile
      args:
        - USE_DEV_REQUIREMENTS=true
    volumes: ['../funding-service-design-fund-application-builder:/app']
    command: ["sh", "-c", "python -m flask db upgrade && python -m debugpy --listen 0.0.0.0:5601 -m flask run --no-debugger --host 0.0.0.0 --port 8080"]
    ports:
      - 8080:8080
      - 5686:5601
    environment:
      - FORM_RUNNER_INTERNAL_HOST=http://form-runner-dc:3009
      - FORM_RUNNER_EXTERNAL_HOST=http://localhost:3009
      - DATABASE_URL=postgresql://postgres:password@fab-db-dc:5432/fund_builder   # pragma: allowlist secret
      - FLASK_DEBUG=0
      - FLASK_ENV=development
      - SECRET_KEY=local
    depends_on: [fab-db-dc, form-runner-dc]

  fab-db-dc:
    image: postgres
    container_name: fab-db-dc
    ports:
      - 5435:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=fund_builder

  form-runner-dc:
    container_name: form-runner-dc
    build:
      context: ../digital-form-builder-adapter
      dockerfile: ./runner/Dockerfile
    ports:
      - "3009:3009"
      - 9228:9228
    command: yarn runner dev
    environment:
      - CHOKIDAR_USEPOLLING=true
      - PREVIEW_MODE=true
      - LAST_COMMIT
      - LAST_TAG
      - JWT_AUTH_ENABLED=false
      - LOG_LEVEL=debug
      - 'NODE_CONFIG={"safelist": ["fab"]}'
      - PREVIEW_MODE=true
      - NODE_ENV=development
