name: funding-service

services:
  pre-award:
    build:
      context: ./apps/funding-service-pre-award
    stdin_open: true
    tty: true
    command: >
      bash -c "
      cp /app-certs/rootCA.pem /usr/local/share/ca-certificates/rootCA.crt && \
      update-ca-certificates && \
      python build.py && \
      invoke common.full-bootstrap && \
      python -m debugpy --listen 0.0.0.0:5678 -m flask -A app:create_app run --host 0.0.0.0 --port 4004 --cert=/app-certs/cert.pem --key=/app-certs/key.pem
      "
    env_file:
      - .env
      - .awslocal.env
    environment:
      - FLASK_ENV=development
      - GOV_NOTIFY_API_KEY=${GOV_NOTIFY_API_KEY:?err}
      - DATABASE_URL=postgresql://postgres:password@database:5432/pre_award_stores
      - FUND_STORE_API_HOST=https://api.levellingup.gov.localhost:4004/fund
      - ACCOUNT_STORE_API_HOST=https://api.levellingup.gov.localhost:4004/account
      - APPLICATION_STORE_API_HOST=https://api.levellingup.gov.localhost:4004/application
      - REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
      - USE_LOCAL_DATA=False
      - FORMS_SERVICE_PUBLIC_HOST=https://form-runner.levellingup.gov.localhost:3009
      - FORMS_SERVICE_PRIVATE_HOST=https://form-runner.levellingup.gov.localhost:3009
      - AUTHENTICATOR_HOST=https://authenticator.levellingup.gov.localhost:4004
      - APPLY_HOST=frontend.levellingup.gov.localhost:3008
      - ASSESS_HOST=assessment.levellingup.gov.localhost:3010
      - API_HOST=api.levellingup.gov.localhost:4004
      - AUTH_HOST=authenticator.levellingup.gov.localhost:4004
      - FLASK_DEBUG=1
      - REDIS_INSTANCE_URI=redis://redis-data:6379
      - SECRET_KEY=dc_key
      - ASSESSMENT_STORE_API_HOST=https://api.levellingup.gov.localhost:4004/assessment
      - APPLICANT_FRONTEND_HOST=https://funding.communities.gov.localhost:3010
      - ASSESSMENT_FRONTEND_HOST=https://funding.communities.gov.localhost:3010
      - POST_AWARD_FRONTEND_HOST=https://find-monitoring-data.levellingup.gov.localhost:4001
      - POST_AWARD_SUBMIT_HOST=https://submit-monitoring-data.levellingup.gov.localhost:4001
      - FUND_APPLICATION_BUILDER_HOST=https://fund-application-builder.levellingup.gov.localhost:3011
      - FORM_DESIGNER_HOST=https://form-designer.levellingup.gov.localhost:3000
      - COOKIE_DOMAIN=.levellingup.gov.localhost
    ports:
      - 4004:4004
      - 3008:4004
      - 3010:4004
      - 5692:5678
    depends_on:
      database:
        condition: service_healthy
      localstack:
        condition: service_started
    volumes:
      - './apps/funding-service-pre-award:/app'
      - './certs:/app-certs'
      - '/app/.venv' # Don't overwrite this directory with local .venv because uv links won't translate in the container
    networks:
      default:
        aliases:
          - api.levellingup.gov.localhost
          - frontend.levellingup.gov.localhost
          - assessment.levellingup.gov.localhost
          - authenticator.levellingup.gov.localhost
          - funding.communities.gov.localhost
    profiles: [ pre, post ]

  redis-data:
    image: redis
    ports:
      - 6379:6379

  database:
    image: postgres
    volumes:
      - ./docker-postgresql-multiple-databases:/docker-entrypoint-initdb.d
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_MULTIPLE_DATABASES=data_store,data_store_test,fab_store,fab_store_test,pre_award_stores,pre_award_stores_test
    ports:
      - 5432:5432
    healthcheck:
      test: pg_isready -U postgres
      interval: 10s
      timeout: 5s
      retries: 5

  localstack:
    image: localstack/localstack:3.7.2
    env_file: .awslocal.env
    environment:
      - SERVICES=s3,sqs
      - PERSISTENCE=1
      - LS_LOG=warn
      - USE_SSL=1
    ports:
      - 4566:4566 # LocalStack endpoint
      - 4510-4559:4510-4559 # external services port range
    volumes:
      - ./docker-localstack:/etc/localstack/init/ready.d
      - localstack:/var/lib/localstack
    networks:
      default:
        aliases:
          - localhost.localstack.cloud

volumes:
  localstack: null

networks:
  default:
