services:
  fund-store:
    build: 
      context: ../funding-service-design-fund-store
    command: ['flask', 'run', '--host', '0.0.0.0', '--port', '8080']
    environment:
      - FLASK_ENV=development
    ports: 
      - 3001:8080
    volumes: ['../funding-service-design-fund-store:/app']
  application-store:
    build: 
      context: ../funding-service-design-application-store
    command: ['flask', 'run', '--host', '0.0.0.0', '--port', '8080']
    environment:
      - FLASK_ENV=development
    ports: 
      - 3002:8080
    volumes: ['../funding-service-design-application-store:/app']
  account-store:
      build: 
        context: ../funding-service-design-account-store
      command: ['flask', 'run', '--host', '0.0.0.0', '--port', '8080']
      environment:
        - FLASK_ENV=development
      volumes: ['../funding-service-design-account-store:/app']
      ports: 
        - 3003:8080
  authenticator:
      build: 
        context: ../funding-service-design-authenticator
      volumes: ['../funding-service-design-authenticator:/app']
      ports: 
        - 3004:8080
      depends_on:
        - authenticator-data
        - account-store
      environment: 
        - REDIS_INSTANCE_URI=redis://authenticator-data:6379
        - ACCOUNT_STORE_API_HOST=http://account-store:8080
        - AUTHENTICATOR_HOST=http://localhost:3004
        - NOTIFICATION_SERVICE_HOST=http://notification:8080
        - APPLICANT_FRONTEND_HOST=http://localhost:3008
  assessment-store:
      build: 
        context: ../funding-service-design-assessment-store
      volumes: ['../funding-service-design-assessment-store:/app']
      ports: 
        - 3005:8080
  notification:
      build: 
        context: ../funding-service-design-notification
      volumes: ['../funding-service-design-notification:/app']
      ports: 
        - 3006:8080
      environment:
        GOV_NOTIFY_API_KEY: ${GOV_NOTIFY_API_KEY:?err}
  fund-discovery-frontend:
    build: 
      context: ../funding-service-design-fund-discovery-frontend
    volumes: ['../funding-service-design-fund-discovery-frontend:/app']
    command: ['flask', 'run', '--host', '0.0.0.0', '--port', '8080']
    depends_on:
      - fund-store
    environment:
      - FLASK_ENV=development
      - AUTHENTICATOR_HOST=http://localhost:3004
      - FUND_STORE_API_HOST=http://fund-store:8080
      - USE_LOCAL_DATA=False
    ports: 
      - 3007:8080
  frontend:
    build:
      context: ../funding-service-design-frontend
      dockerfile: app.dockerfile
    volumes: ['../funding-service-design-frontend:/app']
    depends_on:
      - application-store
      - form-runner
    environment:
      - USE_LOCAL_DATA=False
      - APPLICATION_STORE_API_HOST=http://application-store:8080
      - FORMS_SERVICE_PUBLIC_HOST=http://localhost:3009
    ports:
      - 3008:8080
  form-runner:
    build: 
      context: ../funding-service-design-frontend
    ports: 
      - 3009:3009
  authenticator-data:
    image: redis
    ports:
      - 6379:6379