services:
  fund-store:
    build: 
      context: ../funding-service-design-fund-store
    command: ['flask', 'run', '--host', '0.0.0.0', '--port', '8080']
    environment:
      - FLASK_ENV=development
    ports: 
      - 3001:8080
    volumes: ['../funding-service-design-fund-store:/app']
  application-store:
    build: 
      context: ../funding-service-design-application-store
    command: ['flask', 'run', '--host', '0.0.0.0', '--port', '8080']
    environment:
      - FLASK_ENV=development
    ports: 
      - 3002:8080
    volumes: ['../funding-service-design-fund-store:/app']
  account-store:
      build: 
        context: ../funding-service-design-account-store
      command: ['flask', 'run', '--host', '0.0.0.0', '--port', '8080']
      environment:
        - FLASK_ENV=development
      volumes: ['../funding-service-design-account-store:/app']
      ports: 
        - 3003:8080
  authenticator:
      build: 
        context: ../funding-service-design-authenticator
      volumes: ['../funding-service-design-authenticator:/app']
      ports: 
        - 3004:8080
      depends_on:
        - authenticator-data
  assessment-store:
      build: 
        context: ../funding-service-design-assessment-store
      volumes: ['../funding-service-design-assessment-store:/app']
      ports: 
        - 3005:8080
  notification:
      build: 
        context: ../funding-service-design-notification
      volumes: ['../funding-service-design-notification:/app']
      ports: 
        - 3006:8080
      environment:
        GOV_NOTIFY_API_KEY: ${GOV_NOTIFY_API_KEY:?err}
  form-runner:
    build: 
      context: ../funding-service-design-frontend
    ports: 
      - 3009:3009
  authenticator-data:
    image: redis
    ports:
      - 6379:6379