services:
  fund-store:
    build: 
      context: ../funding-service-design-fund-store
    command: ['flask', 'run', '--host', '0.0.0.0', '--port', '8080']
    environment:
      - FLASK_ENV=development
    ports: 
      - 3002:8080
    volumes: ['../funding-service-design-fund-store:/app']
  account-store:
      build: 
        context: ../funding-service-design-account-store
      command: ['flask', 'run', '--host', '0.0.0.0', '--port', '8080']
      environment:
        - FLASK_ENV=development
      ports: 
        - 3001:8080
  form-runner:
    build: 
      context: ../funding-service-design-frontend
    ports: 
      - 3009:3009