[package]
name = "funding-service-design-fund-application-builder"
version = "0.0.1"
description = "Prototype Fund Application Builder (FAB) app for building application forms"
authors = ["MHCLG"]
license = "MIT License"

[tool.black]
line-length = 120

[tool.flake8]
max-line-length = 120
ignore = ['E203', 'W503']
count = true

[tool.isort]
profile = "black"
force_single_line = "true"
