"""Alter index to allow multiple forms to have pages of the same name

Revision ID: 846793bff0d3
Revises: d69508409404
Create Date: 2024-09-11 07:53:22.075755

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "846793bff0d3"
down_revision = "d69508409404"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("page", schema=None) as batch_op:
        batch_op.drop_index("ix_template_page_name", postgresql_where="(is_template = true)")
        batch_op.create_index(
            "ix_template_page_name",
            ["display_path", "form_id"],
            unique=True,
            postgresql_where="Page.is_template = true",
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("page", schema=None) as batch_op:
        batch_op.drop_index("ix_template_page_name", postgresql_where="Page.is_template = true")
        batch_op.create_index(
            "ix_template_page_name", ["display_path"], unique=True, postgresql_where="(is_template = true)"
        )

    # ### end Alembic commands ###
