"""Adding is_template to list table

Revision ID: eb66c0e87001
Revises: 4247b8f71cff
Create Date: 2024-07-16 08:50:01.637018

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "eb66c0e87001"
down_revision = "4247b8f71cff"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lizt", schema=None) as batch_op:
        batch_op.add_column(sa.Column("is_template", sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lizt", schema=None) as batch_op:
        batch_op.drop_column("is_template")

    # ### end Alembic commands ###
