"""empty message

Revision ID: ab7d40d652d5
Revises: da88c6b36588
Create Date: 2024-08-02 14:52:53.157158

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "ab7d40d652d5"
down_revision = "da88c6b36588"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organisation",
        sa.Column("organisation_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("short_name", sa.String(length=15), nullable=False),
        sa.Column("logo_uri", sa.String(length=100), nullable=True),
        sa.Column("audit_info", postgresql.JSON(none_as_null=True, astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("organisation_id", name=op.f("pk_organisation")),
        sa.UniqueConstraint("name", name=op.f("uq_organisation_name")),
        sa.UniqueConstraint("short_name", name=op.f("uq_organisation_short_name")),
    )
    with op.batch_alter_table("fund", schema=None) as batch_op:
        batch_op.add_column(sa.Column("owner_organisation_id", sa.UUID(), nullable=True))
        batch_op.create_foreign_key(
            batch_op.f("fk_fund_owner_organisation_id_organisation"),
            "organisation",
            ["owner_organisation_id"],
            ["organisation_id"],
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("fund", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("fk_fund_owner_organisation_id_organisation"), type_="foreignkey")
        batch_op.drop_column("owner_organisation_id")

    op.drop_table("organisation")
    # ### end Alembic commands ###
