"""empty message

Revision ID: ed84bb152ee3
Revises: 4ec629449867
Create Date: 2024-08-21 11:23:11.330243

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ed84bb152ee3"
down_revision = "4ec629449867"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("page", schema=None) as batch_op:
        batch_op.add_column(sa.Column("default_next_page_id", sa.UUID(), nullable=True))
        batch_op.create_foreign_key(
            batch_op.f("fk_page_default_next_page_id_page"), "page", ["default_next_page_id"], ["page_id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("page", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("fk_page_default_next_page_id_page"), type_="foreignkey")
        batch_op.drop_column("default_next_page_id")

    # ### end Alembic commands ###
