"""empty message

Revision ID: c3dab74013f1
Revises: ca61d3b746f6
Create Date: 2024-10-03 14:54:03.318048

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "c3dab74013f1"
down_revision = "ca61d3b746f6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("component", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("schema", postgresql.JSON(none_as_null=True, astext_type=sa.Text()), nullable=True)
        )

    with op.batch_alter_table("round", schema=None) as batch_op:
        batch_op.alter_column(
            "application_reminder_sent", existing_type=sa.BOOLEAN(), server_default=None, existing_nullable=False
        )
        batch_op.alter_column(
            "reference_contact_page_over_email",
            existing_type=sa.BOOLEAN(),
            server_default=None,
            existing_nullable=False,
        )
        batch_op.alter_column("support_times", existing_type=sa.VARCHAR(), server_default=None, existing_nullable=False)
        batch_op.alter_column("support_days", existing_type=sa.VARCHAR(), server_default=None, existing_nullable=False)
        batch_op.alter_column(
            "project_name_field_id", existing_type=sa.VARCHAR(), server_default=None, existing_nullable=False
        )
        batch_op.alter_column(
            "all_uploaded_documents_section_available",
            existing_type=sa.BOOLEAN(),
            server_default=None,
            existing_nullable=False,
        )
        batch_op.alter_column(
            "application_fields_download_available",
            existing_type=sa.BOOLEAN(),
            server_default=None,
            existing_nullable=False,
        )
        batch_op.alter_column(
            "display_logo_on_pdf_exports", existing_type=sa.BOOLEAN(), server_default=None, existing_nullable=False
        )
        batch_op.alter_column(
            "mark_as_complete_enabled", existing_type=sa.BOOLEAN(), server_default=None, existing_nullable=False
        )
        batch_op.alter_column(
            "is_expression_of_interest", existing_type=sa.BOOLEAN(), server_default=None, existing_nullable=False
        )
        batch_op.alter_column(
            "section_base_path",
            existing_type=sa.INTEGER(),
            server_default=sa.text("nextval('section_base_path_seq')"),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("round", schema=None) as batch_op:
        batch_op.alter_column(
            "section_base_path",
            existing_type=sa.INTEGER(),
            server_default=sa.text("nextval('section_base_path_seq'::regclass)"),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "is_expression_of_interest",
            existing_type=sa.BOOLEAN(),
            server_default=sa.text("false"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "mark_as_complete_enabled",
            existing_type=sa.BOOLEAN(),
            server_default=sa.text("false"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "display_logo_on_pdf_exports",
            existing_type=sa.BOOLEAN(),
            server_default=sa.text("false"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "application_fields_download_available",
            existing_type=sa.BOOLEAN(),
            server_default=sa.text("false"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "all_uploaded_documents_section_available",
            existing_type=sa.BOOLEAN(),
            server_default=sa.text("false"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "project_name_field_id",
            existing_type=sa.VARCHAR(),
            server_default=sa.text("''::character varying"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "support_days",
            existing_type=sa.VARCHAR(),
            server_default=sa.text("''::character varying"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "support_times",
            existing_type=sa.VARCHAR(),
            server_default=sa.text("''::character varying"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "reference_contact_page_over_email",
            existing_type=sa.BOOLEAN(),
            server_default=sa.text("false"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "application_reminder_sent",
            existing_type=sa.BOOLEAN(),
            server_default=sa.text("false"),
            existing_nullable=False,
        )

    with op.batch_alter_table("component", schema=None) as batch_op:
        batch_op.drop_column("schema")

    # ### end Alembic commands ###
