"""empty message

Revision ID: 7c9fef251eca
Revises: c3dab74013f1
Create Date: 2024-10-04 17:27:35.183466

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "7c9fef251eca"
down_revision = "c3dab74013f1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("page", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("section", postgresql.JSON(none_as_null=True, astext_type=sa.Text()), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("page", schema=None) as batch_op:
        batch_op.drop_column("section")

    # ### end Alembic commands ###
