"""empty message

Revision ID: 5e2362840f43
Revises: c3ad6fc2300d
Create Date: 2024-09-26 12:05:19.295518

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5e2362840f43"
down_revision = "c3ad6fc2300d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("component", schema=None) as batch_op:
        batch_op.alter_column("runner_component_name", existing_type=sa.VARCHAR(), nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("component", schema=None) as batch_op:
        batch_op.alter_column("runner_component_name", existing_type=sa.VARCHAR(), nullable=False)

    # ### end Alembic commands ###
