"""Rename template name columns

Revision ID: 5c63de4e4e49
Revises: e58b1e674060
Create Date: 2024-07-17 12:02:11.799787

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5c63de4e4e49"
down_revision = "e58b1e674060"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("component", schema=None) as batch_op:
        batch_op.add_column(sa.Column("template_name", sa.String(), nullable=True))
        batch_op.drop_column("Template Name")

    with op.batch_alter_table("form", schema=None) as batch_op:
        batch_op.add_column(sa.Column("template_name", sa.String(), nullable=True))
        batch_op.drop_column("Template Name")

    with op.batch_alter_table("page", schema=None) as batch_op:
        batch_op.add_column(sa.Column("template_name", sa.String(), nullable=True))
        batch_op.drop_column("Template Name")

    with op.batch_alter_table("section", schema=None) as batch_op:
        batch_op.add_column(sa.Column("template_name", sa.String(), nullable=True))
        batch_op.drop_column("Template Name")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("section", schema=None) as batch_op:
        batch_op.add_column(sa.Column("Template Name", sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column("template_name")

    with op.batch_alter_table("page", schema=None) as batch_op:
        batch_op.add_column(sa.Column("Template Name", sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column("template_name")

    with op.batch_alter_table("form", schema=None) as batch_op:
        batch_op.add_column(sa.Column("Template Name", sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column("template_name")

    with op.batch_alter_table("component", schema=None) as batch_op:
        batch_op.add_column(sa.Column("Template Name", sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column("template_name")

    # ### end Alembic commands ###
