"""empty message

Revision ID: da88c6b36588
Revises: 3de2807b6917
Create Date: 2024-07-19 13:20:24.997440

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "da88c6b36588"
down_revision = "3de2807b6917"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("round", schema=None) as batch_op:
        batch_op.add_column(sa.Column("prospectus_link", sa.String(), nullable=False))
        batch_op.add_column(sa.Column("privacy_notice_link", sa.String(), nullable=False))
        batch_op.drop_column("privacy_notice")
        batch_op.drop_column("prospectus")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("round", schema=None) as batch_op:
        batch_op.add_column(sa.Column("prospectus", sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column("privacy_notice", sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column("privacy_notice_link")
        batch_op.drop_column("prospectus_link")

    # ### end Alembic commands ###
