"""add section_base_path and sequence

Revision ID: ca61d3b746f6
Revises: 5e2362840f43
Create Date: 2024-10-01 11:18:13.774238

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision = "ca61d3b746f6"
down_revision = "5e2362840f43"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("round", schema=None) as batch_op:
        op.execute(text("CREATE SEQUENCE section_base_path_seq START WITH 1001"))
        batch_op.add_column(
            sa.Column(
                "section_base_path",
                sa.Integer(),
                server_default=sa.text("nextval('section_base_path_seq')"),
                nullable=True,
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("round", schema=None) as batch_op:
        batch_op.drop_column("section_base_path")
    with op.batch_alter_table("round", schema=None) as batch_op:
        op.execute(text("DROP SEQUENCE section_base_path_seq"))

    # ### end Alembic commands ###
