"""empty message

Revision ID: 3de2807b6917
Revises: 3fffc621bff4
Create Date: 2024-07-19 12:33:29.898715

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3de2807b6917"
down_revision = "3fffc621bff4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("round", schema=None) as batch_op:
        batch_op.add_column(sa.Column("source_template_id", sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column("template_name", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("round", schema=None) as batch_op:
        batch_op.drop_column("template_name")
        batch_op.drop_column("source_template_id")

    # ### end Alembic commands ###
