"""Add unique index on Page.display_path when is_template is true

Revision ID: e58b1e674060
Revises: eb66c0e87001
Create Date: 2024-07-16 09:21:52.877957

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "e58b1e674060"
down_revision = "eb66c0e87001"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("page", schema=None) as batch_op:
        batch_op.create_index(
            "ix_template_page_name", ["display_path"], unique=True, postgresql_where="Page.is_template = true"
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("page", schema=None) as batch_op:
        batch_op.drop_index("ix_template_page_name", postgresql_where="Page.is_template = true")

    # ### end Alembic commands ###
